# ----- inference config -----
prompt: "a king on a throne"
negative_prompt: ""
seed: 42
input_image: null # a path for img2img, or null for txt2img
strength: 0.8 # img2img only
lora_path: data/weights/persian_lora.safetensors  # null for base model inference
pretrained_path: data/weights/v1-5-pruned-emaonly.safetensors
device: cuda
sampler: ddpm
n_steps: 50
guidance_scale: 7.5
