# ----- LoRA finetuning run configs -----
name: lora

# model / paths
pretrained_path: data/weights/v1-5-pruned-emaonly.safetensors
device: cuda

# data
dataset: naruto

# lora
r: 16
alpha: 16
targets:
  desc: selfcross
  layers: ["q1", "k1", "v1", "proj_out1", "q2", "k2", "v2", "proj_out2"]

# training
n_epochs: 10
batch_size: 4
lr: 0.0001
seed: 42
log_interval: 1
